package flavorvault;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class AddNewRecipePage extends javax.swing.JFrame {

    /**
     * Creates new form AddNewRecipePage
     */
    public AddNewRecipePage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        IngredientsField = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        DishNameField = new javax.swing.JTextField();
        CategoryComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        InstructionsField = new javax.swing.JTextPane();
        HomeButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 246, 236));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngredientsField.setBackground(new java.awt.Color(255, 255, 255));
        IngredientsField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        IngredientsField.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(IngredientsField);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, 280));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Title");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 40, 30));

        DishNameField.setBackground(new java.awt.Color(255, 255, 255));
        DishNameField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        DishNameField.setForeground(new java.awt.Color(0, 0, 0));
        DishNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DishNameField.setText("Name of Food/Dish");
        DishNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DishNameFieldActionPerformed(evt);
            }
        });
        jPanel6.add(DishNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 530, 40));

        CategoryComboBox.setBackground(new java.awt.Color(255, 255, 255));
        CategoryComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        CategoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main Dishes", "Appetizers", "Side Dishes", "Soups", "Salads", "Desserts", "Snacks", "Beverages", "Sauces & Dips", "Breakfast", "Lunch", "Dinner" }));
        CategoryComboBox.setOpaque(true);
        CategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryComboBoxActionPerformed(evt);
            }
        });
        jPanel6.add(CategoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 150, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Category");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 80, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingredients");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Instructions");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, 30));

        SaveButton.setBackground(new java.awt.Color(0, 0, 0));
        SaveButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("SAVE");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel6.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 110, 40));

        CancelButton.setBackground(new java.awt.Color(229, 229, 229));
        CancelButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelButton.setText("CANCEL");
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        jPanel6.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 110, 40));

        InstructionsField.setBackground(new java.awt.Color(255, 255, 255));
        InstructionsField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        InstructionsField.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(InstructionsField);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 530, 280));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 890, 480));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home Button.png"))); // NOI18N
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo with Text.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background Image.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryComboBoxActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String recipeName = DishNameField.getText().trim();
        String ingredients = IngredientsField.getText().trim();
        String instructions = InstructionsField.getText().trim();
        String selectedCategory = (String) CategoryComboBox.getSelectedItem();
        

        // Replace this with how you're storing the current user's ID
        int currentUserId = SessionManager.getCurrentUserId(); // Example: You must manage the logged-in user's ID

        // Validate input
        if (recipeName.isEmpty() || ingredients.isEmpty() || instructions.isEmpty() || selectedCategory == null) {
            JOptionPane.showMessageDialog(this, "Please fill out all fields.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // DB connection variables
        String url = "jdbc:mysql://localhost:3306/flavor_vault";
        String dbUser = "root";
        String dbPass = "8472252Adrielle!";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(url, dbUser, dbPass);

            // Get category_id from category name
            String categoryQuery = "SELECT category_id FROM categories WHERE name = ?";
            PreparedStatement catStmt = conn.prepareStatement(categoryQuery);
            catStmt.setString(1, selectedCategory);
            ResultSet rs = catStmt.executeQuery();

            int categoryId = -1;
            if (rs.next()) {
                categoryId = rs.getInt("category_id");
            } else {
                JOptionPane.showMessageDialog(this, "Category not found.", "Database Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Insert recipe
            String insertQuery = "INSERT INTO recipes (user_id, category_id, name, ingredients, instructions) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
            insertStmt.setInt(1, currentUserId);
            insertStmt.setInt(2, categoryId);
            insertStmt.setString(3, recipeName);
            insertStmt.setString(4, ingredients);
            insertStmt.setString(5, instructions);

            int rowsInserted = insertStmt.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Recipe saved successfully!");
                // Go back to landing 
                String username = SessionManager.getCurrentUsername();
                LandingPage home = new LandingPage();
                home.setUsername(username);
                home.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save the recipe.");
            }

            rs.close();
            catStmt.close();
            insertStmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        // TODO add your handling code here:
        String username = SessionManager.getCurrentUsername();
        LandingPage home = new LandingPage();
        home.setUsername(username);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        String username = SessionManager.getCurrentUsername();
        LandingPage cancel = new LandingPage();
        cancel.setUsername(username);
        cancel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void DishNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DishNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DishNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewRecipePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewRecipePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewRecipePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewRecipePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewRecipePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JTextField DishNameField;
    private javax.swing.JLabel HomeButton;
    private javax.swing.JTextPane IngredientsField;
    private javax.swing.JTextPane InstructionsField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
