/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flavorvault;

/**
 *
 * @author Asus
 */
public class LandingPage extends javax.swing.JFrame {
private String username;
    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents(); 
        setLocationRelativeTo(null);
    }
    
        public LandingPage(String username){
        initComponents();
        setUsername(username);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutButton = new javax.swing.JButton();
        ViewSavedRecipesButton = new javax.swing.JButton();
        AddNewRecipeButton = new javax.swing.JButton();
        TimerButton = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOutButton.setBackground(new java.awt.Color(0, 0, 0));
        LogOutButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogOutButton.setText("LOG-OUT");
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 180, 50));

        ViewSavedRecipesButton.setBackground(new java.awt.Color(0, 0, 0));
        ViewSavedRecipesButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        ViewSavedRecipesButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewSavedRecipesButton.setText("VIEW SAVED RECIPES");
        ViewSavedRecipesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewSavedRecipesButtonMouseClicked(evt);
            }
        });
        ViewSavedRecipesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSavedRecipesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewSavedRecipesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 180, 50));

        AddNewRecipeButton.setBackground(new java.awt.Color(0, 0, 0));
        AddNewRecipeButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        AddNewRecipeButton.setForeground(new java.awt.Color(255, 255, 255));
        AddNewRecipeButton.setText("ADD NEW RECIPE");
        AddNewRecipeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewRecipeButtonMouseClicked(evt);
            }
        });
        AddNewRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewRecipeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddNewRecipeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 180, 50));

        TimerButton.setBackground(new java.awt.Color(0, 0, 0));
        TimerButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        TimerButton.setForeground(new java.awt.Color(255, 255, 255));
        TimerButton.setText("TIMER");
        TimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(TimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 180, 50));

        Username.setBackground(new java.awt.Color(255, 255, 153));
        Username.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 50)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setText("Hi, (username)!");
        Username.setOpaque(true);
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 380, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo with Text.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background Image.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUsername(String username) {
        Username.setText("Hi, " + username + "!");
    }
    
    private void ViewSavedRecipesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSavedRecipesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewSavedRecipesButtonActionPerformed

    private void AddNewRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewRecipeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewRecipeButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void AddNewRecipeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewRecipeButtonMouseClicked
        // TODO add your handling code here:
        AddNewRecipePage recipe = new AddNewRecipePage();
        recipe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddNewRecipeButtonMouseClicked
    private void ViewSavedRecipesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewSavedRecipesButtonMouseClicked
        // TODO add your handling code here:
        ViewRecipePage recipes = new ViewRecipePage(username);
        recipes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewSavedRecipesButtonMouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        // TODO add your handling code here:
        RegistrationPage logout = new RegistrationPage();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutButtonMouseClicked

    private void TimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimerButtonMouseClicked
        TimerPage timer = new TimerPage();
        timer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TimerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewRecipeButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton TimerButton;
    private javax.swing.JLabel Username;
    private javax.swing.JButton ViewSavedRecipesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
