package flavorvault;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginUsername = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        CreateAnAccount = new javax.swing.JLabel();
        NeedHelpButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginUsername.setBackground(new java.awt.Color(255, 255, 255));
        LoginUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginUsername.setText("Enter Username");
        LoginUsername.setDragEnabled(true);
        LoginUsername.setName(""); // NOI18N
        LoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(LoginUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 220, 50));

        LoginPassword.setBackground(new java.awt.Color(255, 255, 255));
        LoginPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginPassword.setText("jPasswordField1");
        LoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(LoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 220, 50));

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("LOG-IN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 180, 50));

        CreateAnAccount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        CreateAnAccount.setForeground(new java.awt.Color(0, 0, 0));
        CreateAnAccount.setText("<html><u>Create an Account</u></html>");
        CreateAnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAnAccountMouseClicked(evt);
            }
        });
        getContentPane().add(CreateAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        NeedHelpButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        NeedHelpButton.setForeground(new java.awt.Color(0, 0, 0));
        NeedHelpButton.setText("<html><u>Need Help?</u></html>");
        NeedHelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NeedHelpButtonMouseClicked(evt);
            }
        });
        getContentPane().add(NeedHelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log-In Page Text.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo No Text.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/[OOP] Flavor Vault Prototype.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1240, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
            String username = LoginUsername.getText().trim();
            String password = new String(LoginPassword.getPassword()).trim(); // if using JPasswordField

            // Basic input validation
            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username and password cannot be empty.", "Login Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Database connection
            String url = "jdbc:mysql://localhost:3306/flavor_vault";
            String dbUser = "root";
            String dbPass = "8472252Adrielle!";

            try {
                // Load driver
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection(url, dbUser, dbPass);

                // SQL to check credentials
                String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, username);
                stmt.setString(2, password);

                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    int fetchedUserId = rs.getInt("user_id");

                    SessionManager.setCurrentUserId(fetchedUserId);
                    JOptionPane.showMessageDialog(this, "Login successful. Welcome, " + username + "!");
                    
                    SessionManager.setCurrentUsername(username);
                    
                    // Go to Landing Page
                    LandingPage landing = new LandingPage(username);
                    landing.setVisible(true);
                    this.dispose();
                } else {
                    // Login failed
                    JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                }

                // Close
                rs.close();
                stmt.close();
                conn.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
                e.printStackTrace();
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CreateAnAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAnAccountMouseClicked
        RegistrationPage register = new RegistrationPage();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CreateAnAccountMouseClicked

    private void LoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsernameActionPerformed

    private void LoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPasswordActionPerformed

    private void NeedHelpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NeedHelpButtonMouseClicked
        NeedHelpLogIn help2 = new NeedHelpLogIn();
        help2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NeedHelpButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateAnAccount;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JLabel NeedHelpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
