/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flavorvault;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class TimerPage extends javax.swing.JFrame {
    
    private Timer countdownTimer;
    private int remainingSeconds;
    private boolean isPaused = false;

    public TimerPage() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StopTimer = new javax.swing.JButton();
        StartTimer = new javax.swing.JButton();
        ResetTimer = new javax.swing.JButton();
        SecondsField = new javax.swing.JTextField();
        HoursField = new javax.swing.JTextField();
        MinutesField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TimerCount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StopTimer.setBackground(new java.awt.Color(229, 229, 229));
        StopTimer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        StopTimer.setForeground(new java.awt.Color(0, 0, 0));
        StopTimer.setText("STOP");
        StopTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopTimerActionPerformed(evt);
            }
        });
        getContentPane().add(StopTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 130, 50));

        StartTimer.setBackground(new java.awt.Color(0, 0, 0));
        StartTimer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        StartTimer.setForeground(new java.awt.Color(255, 255, 255));
        StartTimer.setText("START");
        StartTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTimerActionPerformed(evt);
            }
        });
        getContentPane().add(StartTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 130, 50));

        ResetTimer.setBackground(new java.awt.Color(204, 204, 204));
        ResetTimer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        ResetTimer.setForeground(new java.awt.Color(0, 0, 0));
        ResetTimer.setText("RESET");
        ResetTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetTimerActionPerformed(evt);
            }
        });
        getContentPane().add(ResetTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 130, 50));

        SecondsField.setBackground(new java.awt.Color(255, 255, 255));
        SecondsField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SecondsField.setForeground(new java.awt.Color(0, 0, 0));
        SecondsField.setText("0");
        SecondsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SecondsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 100, 40));

        HoursField.setBackground(new java.awt.Color(255, 255, 255));
        HoursField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HoursField.setForeground(new java.awt.Color(0, 0, 0));
        HoursField.setText("0");
        HoursField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoursFieldActionPerformed(evt);
            }
        });
        getContentPane().add(HoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 100, 40));

        MinutesField.setBackground(new java.awt.Color(255, 255, 255));
        MinutesField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MinutesField.setForeground(new java.awt.Color(0, 0, 0));
        MinutesField.setText("0");
        MinutesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutesFieldActionPerformed(evt);
            }
        });
        getContentPane().add(MinutesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 100, 40));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Seconds");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Minutes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hours");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        TimerCount.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 130)); // NOI18N
        TimerCount.setForeground(new java.awt.Color(0, 0, 0));
        TimerCount.setText("00:00:00");
        getContentPane().add(TimerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo with Text.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home Button.png"))); // NOI18N
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background Image.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1160, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        // TODO add your handling code here:
        String username = SessionManager.getCurrentUsername();
        LandingPage home = new LandingPage(username);
        home.setUsername(username);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void StopTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopTimerActionPerformed
        if (countdownTimer != null && countdownTimer.isRunning()) {
            countdownTimer.stop();
            isPaused = true;
        }
    }//GEN-LAST:event_StopTimerActionPerformed

    private void StartTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTimerActionPerformed
            try {
            // If paused, just resume the timer
            if (isPaused && countdownTimer != null) {
                countdownTimer.start();
                isPaused = false;
                return;
            }

            // Otherwise, this is a fresh start — stop old timer
            if (countdownTimer != null) {
                countdownTimer.stop();
                countdownTimer = null;
            }

            // Read input fields only on fresh start
            int hours = Integer.parseInt(HoursField.getText().trim());
            int minutes = Integer.parseInt(MinutesField.getText().trim());
            int seconds = Integer.parseInt(SecondsField.getText().trim());

            remainingSeconds = (hours * 3600) + (minutes * 60) + seconds;

            if (remainingSeconds <= 0) {
                JOptionPane.showMessageDialog(this, "Enter a time greater than 0.");
                return;
            }

            // Lock fields
            HoursField.setEditable(false);
            MinutesField.setEditable(false);
            SecondsField.setEditable(false);

            countdownTimer = new Timer(1000, new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    if (remainingSeconds > 0) {
                        remainingSeconds--;

                        int hrs = remainingSeconds / 3600;
                        int mins = (remainingSeconds % 3600) / 60;
                        int secs = remainingSeconds % 60;

                        TimerCount.setText(String.format("%02d:%02d:%02d", hrs, mins, secs));
                    } else {
                        countdownTimer.stop();
                        new TimesUp().setVisible(true);
                        isPaused = false;
                    }
                }
            });

            countdownTimer.start();
            isPaused = false;

        } catch (NumberFormatException ex){
            new EnterValidValues().setVisible(true);
        }
    }//GEN-LAST:event_StartTimerActionPerformed

    private void ResetTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetTimerActionPerformed
        if (countdownTimer != null) {
            countdownTimer.stop();
            countdownTimer = null;
        }
        
        isPaused = false;
        
        // Reset UI
        TimerCount.setText("00:00:00");
        HoursField.setText("0");
        MinutesField.setText("0");
        SecondsField.setText("0");

        HoursField.setEditable(true);
        MinutesField.setEditable(true);
        SecondsField.setEditable(true);
    }//GEN-LAST:event_ResetTimerActionPerformed

    private void HoursFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoursFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoursFieldActionPerformed

    private void MinutesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinutesFieldActionPerformed

    private void SecondsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondsFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TimerPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeButton;
    private javax.swing.JTextField HoursField;
    private javax.swing.JTextField MinutesField;
    private javax.swing.JButton ResetTimer;
    private javax.swing.JTextField SecondsField;
    private javax.swing.JButton StartTimer;
    private javax.swing.JButton StopTimer;
    private javax.swing.JLabel TimerCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
